# Generated by Django 4.2 on 2025-02-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itinerary",
            name="location",
        ),
        migrations.AddField(
            model_name="itinerary",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itinerary",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itinerary",
            name="planning_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
